name: Build macOS distribution

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt5 python-telegram-bot pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-bundle
          path: dist/telegram_publisher_mac